name: Firebase CI/CD

on:
  push:
    branches:
      - develop_hub
      - main
  pull_request:
    branches:
      - develop_hub
      - main

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 20.x ]

    environment: ${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Set up Node.js
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install PNPM
        run: npm install -g pnpm
      - name: Install Dependencies
        run: pnpm install
      - name: Build production
        env:
          REACT_APP_BASE_URL: ${{ vars.REACT_APP_BASE_URL }}
        run: pnpm run build
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: build
          path: build

  deploy:
    name: Deploy to Firebase
    needs: build
    runs-on: ubuntu-latest

    environment: ${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: build
          path: build
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}-hladmin
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
          PROJECT_ID: ${{ vars.GOOGLE_CLOUD_PROJECT }}
